import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/__docusaurus/debug',
    component: ComponentCreator('/__docusaurus/debug', 'dd6'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/config',
    component: ComponentCreator('/__docusaurus/debug/config', 'a7f'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/content',
    component: ComponentCreator('/__docusaurus/debug/content', '6f6'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/globalData',
    component: ComponentCreator('/__docusaurus/debug/globalData', 'e5d'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/metadata',
    component: ComponentCreator('/__docusaurus/debug/metadata', 'b2e'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/registry',
    component: ComponentCreator('/__docusaurus/debug/registry', 'ce0'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/routes',
    component: ComponentCreator('/__docusaurus/debug/routes', '3bc'),
    exact: true
  },
  {
    path: '/mdd',
    component: ComponentCreator('/mdd', 'ebb'),
    exact: true
  },
  {
    path: '/docs',
    component: ComponentCreator('/docs', 'b7c'),
    routes: [
      {
        path: '/docs',
        component: ComponentCreator('/docs', '69e'),
        routes: [
          {
            path: '/docs',
            component: ComponentCreator('/docs', '3ec'),
            routes: [
              {
                path: '/docs/create-a-page',
                component: ComponentCreator('/docs/create-a-page', 'e08'),
                exact: true,
                sidebar: "mySidebar"
              },
              {
                path: '/docs/create-doc',
                component: ComponentCreator('/docs/create-doc', '5d6'),
                exact: true,
                sidebar: "mySidebar"
              },
              {
                path: '/docs/deploy-your-site',
                component: ComponentCreator('/docs/deploy-your-site', '517'),
                exact: true,
                sidebar: "mySidebar"
              },
              {
                path: '/docs/introduction',
                component: ComponentCreator('/docs/introduction', '00d'),
                exact: true,
                sidebar: "mySidebar"
              },
              {
                path: '/docs/sidebar',
                component: ComponentCreator('/docs/sidebar', 'bd1'),
                exact: true,
                sidebar: "mySidebar"
              },
              {
                path: '/docs/sidebar/autogenerated',
                component: ComponentCreator('/docs/sidebar/autogenerated', '44b'),
                exact: true,
                sidebar: "mySidebar"
              },
              {
                path: '/docs/sidebar/items',
                component: ComponentCreator('/docs/sidebar/items', '19a'),
                exact: true,
                sidebar: "mySidebar"
              },
              {
                path: '/docs/sidebar/multiple-sidebars',
                component: ComponentCreator('/docs/sidebar/multiple-sidebars', '7d5'),
                exact: true,
                sidebar: "mySidebar"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    path: '/',
    component: ComponentCreator('/', '432'),
    exact: true
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
